# Generated by Django 3.0.5 on 2020-05-09 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizer', '0003_auto_20200502_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=20)),
                ('total_score', models.FloatField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GoGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('black_score', models.FloatField()),
                ('white_score', models.FloatField()),
                ('black', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1', to='organizer.GoPlayer')),
                ('white', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player2', to='organizer.GoPlayer')),
            ],
        ),
    ]
