# Generated by Django 3.0.5 on 2020-05-09 14:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0004_gogame_goplayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='gogame',
            name='date',
            field=models.DateField(default=datetime.date(2020, 5, 9)),
        ),
    ]
