# Generated by Django 3.0.5 on 2020-05-09 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0005_gogame_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='goplayer',
            name='draws',
            field=models.IntegerField(default=0),
        ),
    ]
