# Generated by Django 3.0.5 on 2020-05-12 00:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0006_goplayer_draws'),
    ]

    operations = [
        migrations.AddField(
            model_name='goplayer',
            name='ranking',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='gogame',
            name='date',
            field=models.DateField(default=datetime.date(2020, 5, 12)),
        ),
    ]
