# Generated by Django 3.0.5 on 2020-05-24 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0009_auto_20200524_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='expected_distance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='fuel_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='ticket_per_person',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='cost_per_person',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='trip',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='total_cost',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
