# Generated by Django 3.0.5 on 2020-05-24 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0010_auto_20200524_2057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tripcost',
            old_name='split',
            new_name='one_person_cost',
        ),
        migrations.AddField(
            model_name='trip',
            name='fuel_consumption',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
