# Generated by Django 3.0.5 on 2020-05-24 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0011_auto_20200524_2204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='ticket_per_person',
            new_name='plane_ticket_per_person',
        ),
        migrations.AddField(
            model_name='trip',
            name='train_ticket_per_person',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
