# Generated by Django 3.0.5 on 2020-06-21 13:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0013_auto_20200602_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='maps',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gogame',
            name='date',
            field=models.DateField(default=datetime.date(2020, 6, 21)),
        ),
        migrations.AlterField(
            model_name='trip',
            name='duration',
            field=models.DurationField(null=True),
        ),
    ]
