# Generated by Django 3.0.5 on 2020-06-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0014_auto_20200621_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='duration',
            field=models.IntegerField(null=True),
        ),
    ]
