# Generated by Django 3.0.5 on 2020-06-21 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0015_auto_20200621_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='duration',
        ),
    ]
