# Generated by Django 3.0.5 on 2020-06-21 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0016_remove_trip_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='duration',
            field=models.IntegerField(null=True),
        ),
    ]
