# Generated by Django 3.0.5 on 2020-07-05 21:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0017_trip_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gogame',
            name='date',
            field=models.DateField(default=datetime.date(2020, 7, 5)),
        ),
    ]
