# Generated by Django 3.0.5 on 2020-07-06 22:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0018_auto_20200705_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gogame',
            name='date',
            field=models.DateField(default=datetime.date(2020, 7, 7)),
        ),
    ]
